global:
  scrape_interval: 20s #scrapes metrics every 20 seconds

scrape_configs:
#tells prometheys which endpoints to scrape every interval
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'flask'
    static_configs:
      - targets: ['web:5000']



